#!/usr/bin/env python3
"""
make_kernel_embed.py — embed havendos.elf as a C byte array in kernel_elf.h
Usage: python3 make_kernel_embed.py havendos.elf include/kernel_elf.h
"""
import sys, os

elf_path, out_path = sys.argv[1], sys.argv[2]

with open(elf_path, 'rb') as f:
    data = f.read()

# Verify it's actually an ELF
assert data[:4] == b'\x7fELF', f"Not an ELF file: {elf_path}"

size = len(data)

with open(out_path, 'w') as f:
    f.write("/* Auto-generated by make_kernel_embed.py — DO NOT EDIT */\n")
    f.write("#ifndef KERNEL_ELF_H\n#define KERNEL_ELF_H\n\n")
    f.write(f"static const uint32_t kernel_elf_size = {size}u;\n\n")
    f.write("static const uint8_t kernel_elf_data[] = {\n")
    for i in range(0, size, 16):
        chunk = data[i:i+16]
        f.write("    " + ", ".join(f"0x{b:02X}" for b in chunk))
        if i + 16 < size:
            f.write(",")
        f.write("\n")
    f.write("};\n\n#endif /* KERNEL_ELF_H */\n")

print(f"kernel_elf.h written: {size} bytes ({size//1024}KB)")
